# Generated by Django 6.0.6 on 2026-06-17 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeprecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sleeprecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='weathersnapshot',
            name='weather_condition',
        ),
    ]
