# Generated by Django 6.0.6 on 2026-06-18 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_sleeprecord_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weathersnapshot',
            name='sleep_record',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.CreateModel(
            name='SleepDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сна')),
                ('bedtime', models.DateTimeField(verbose_name='Время засыпания')),
                ('wake_time', models.DateTimeField(verbose_name='Время пробуждения')),
                ('sleep_quality', models.IntegerField(choices=[(1, '⭐ Ужасно'), (2, '⭐⭐ Плохо'), (3, '⭐⭐⭐ Нормально'), (4, '⭐⭐⭐⭐ Хорошо'), (5, '⭐⭐⭐⭐⭐ Отлично')], verbose_name='Качество сна')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.FloatField(verbose_name='Давление (мм рт. ст.)')),
                ('humidity', models.FloatField(verbose_name='Влажность (%)')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('moon_phase', models.CharField(max_length=50, verbose_name='Фаза Луны')),
                ('weather_condition', models.CharField(blank=True, max_length=100, verbose_name='Погодные условия')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('sleep_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='main.sleepdiary')),
            ],
        ),
        migrations.DeleteModel(
            name='SleepRecord',
        ),
        migrations.DeleteModel(
            name='WeatherSnapshot',
        ),
    ]
